package net.minestom.codegen;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.palantir.javapoet.*;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.lang.model.element.Modifier;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public record PropertyGenerator(InputStream blocksFile, Path outputFolder) implements MinestomCodeGenerator {
    private static final String packageName = "net.minestom.server.instance.block.property";
    private static final String enumsPackageName = packageName + ".enums";

    private static final Map<Set<String>, String> MULTI_PROPERTY_ENUM_NAMES = Map.of(
            Set.of("north", "east", "south", "west"), "side"
    );

    private static final Map<List<String>, Map<String, String>> NAME_MODIFIERS = Map.ofEntries(
            Map.entry(List.of("north", "south", "west", "east"), Map.of("facing", "horizontal")),
            Map.entry(List.of("upper", "lower"), Map.of("half", "double_block")),
//            Map.entry(List.of("top", "bottom"), Map.of("half", "block")),
            Map.entry(
                List.of("north_south", "east_west", "ascending_east", "ascending_west", "ascending_north", "ascending_south"),
                Map.of("shape", "straight")
            ),
            Map.entry(List.of("floor", "wall", "ceiling"), Map.of("face", "attach"))
    );

    @Override
    public void generate() {
        ensureDirectory(outputFolder);

        // collect properties
        final Properties properties = new Properties();
        final JsonObject json = GSON.fromJson(new InputStreamReader(blocksFile), JsonObject.class);
        json.entrySet().forEach((entry) -> {
            final JsonElement propertiesElement = entry.getValue().getAsJsonObject().get("properties");
            if (propertiesElement == null) return; // block doesn't have properties
            // ignore the namespace
            final String simpleBlockIdentifier = entry.getKey().substring(entry.getKey().indexOf(':') + 1);
            final JsonObject blockProperties = propertiesElement.getAsJsonObject();
            properties.registerProperties(new Identifier(simpleBlockIdentifier), blockProperties);
        });

        final ClassName implCN = ClassName.get(packageName, "Property");
        final ClassName generatedCN = ClassName.get(packageName, "Properties");
        final TypeSpec.Builder builder = TypeSpec.interfaceBuilder(generatedCN)
                .addModifiers(Modifier.SEALED)
                .addPermittedSubclass(implCN)
                .addAnnotation(AnnotationSpec.builder(SuppressWarnings.class)
                        // ignore DataFlowIssue, IDEA thinks that T::typedValueOf shouldn't return null.
                        .addMember("value", "{\"unused\", \"DataFlowIssue\"}").build())
                .addJavadoc("AUTOGENERATED by " + getClass().getSimpleName());

        final Set<Identifier> usedIdentifiers = new HashSet<>();

        // write boolean properties
        final ClassName booleanPropertyImplCN = ClassName.get(packageName, "BooleanProperty");
        final ParameterizedTypeName booleanProperty = ParameterizedTypeName.get(implCN, TypeName.get(Boolean.class));
        properties.properties.remove(List.of("true", "false")).properties.forEach((name, property) -> {
            final Identifier fieldIdentifier = property.getIdentifier();
            usedIdentifiers.add(fieldIdentifier);
            builder.addField(FieldSpec
                    .builder(booleanProperty, fieldIdentifier.constantName())
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("new $T($S)", booleanPropertyImplCN, name).build());
        });
        // write integer properties
        final ClassName integerPropertyImplCN = ClassName.get(packageName, "IntegerProperty");
        final ParameterizedTypeName integerProperty = ParameterizedTypeName.get(implCN, TypeName.get(Integer.class));
        final Map<String, Property> integerProperties = new LinkedHashMap<>();
        properties.properties.entrySet().removeIf(entry -> {
            if (entry.getValue().type() != 1) return false; // not integer property
            entry.getValue().properties.forEach((name, property) ->
                    integerProperties.computeIfAbsent(name, _ -> new Property(name, List.of()))
                            .registerBlocks(property.blocks));
            return true;
        });
        integerProperties.forEach((name, property) -> {
            Identifier fieldIdentifier = property.getIdentifier();
            if (!usedIdentifiers.add(fieldIdentifier)) {
                fieldIdentifier = fieldIdentifier.withPrefix(new String[]{"int"});
                if (!usedIdentifiers.add(fieldIdentifier)) {
                    throw new RuntimeException("name collision for '" + name + "'");
                }
            }
            builder.addField(FieldSpec
                    .builder(integerProperty, property.getIdentifier().constantName())
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("new $T($S)", integerPropertyImplCN, name).build());
        });

        properties.cleanEnums();
        writeEnumProperties(properties, usedIdentifiers, builder, implCN);
        writeFiles(JavaFile.builder(packageName, builder.build()).indent("    ").build());
    }

    private void writeEnumProperties(
            Properties properties,
            Set<Identifier> usedIdentifiers,
            TypeSpec.Builder builder,
            ClassName implCN
    ) {
        final Map<Identifier, PropertyValues> propertyEnums = new HashMap<>();
        final Map<Identifier, NamedProperty> propertyFields = new LinkedHashMap<>();
        properties.properties.values().stream().flatMap(
                propertyValues -> propertyValues.split == null ?
                        Stream.of(propertyValues) : Stream.concat(Stream.of(propertyValues), propertyValues.split.stream())
        ).forEach(propertyValues -> {
            Stream.concat(
                    propertyValues.properties.values().stream(),
                    propertyValues.subsets.values().stream()
                            .flatMap(subset -> subset.properties.values().stream())
            ).forEach(property -> {
                final Identifier propertyIdentifier = property.getIdentifier();
                if (usedIdentifiers.contains(propertyIdentifier)) {
                    throw new RuntimeException("please add a name modifier for property '" + property.name +
                            "' with values " + property.values);
                }
                final NamedProperty collision = propertyFields.put(
                        propertyIdentifier, new NamedProperty(propertyValues.getIdentifier(), property));
                if (collision != null) {
                    throw new RuntimeException("please add a name modifier for property '" + property.name +
                            "' with values " + property.values +
                            " and/or property '" + collision.property.name +
                            "' with values " + collision.property.values);
                }
            });
            final Identifier enumName = propertyValues.getIdentifier();
            final PropertyValues collision = propertyEnums.put(enumName, propertyValues);
            if (collision != null) {
                final Set<String> propertiesA = new HashSet<>(propertyValues.properties.keySet());
                propertyValues.subsets.forEach((_, subset) ->
                        propertiesA.addAll(subset.properties.keySet()));
                final Set<String> propertiesB = new HashSet<>(collision.properties.keySet());
                collision.subsets.forEach((_, subset) ->
                        propertiesA.addAll(subset.properties.keySet()));

                throw new RuntimeException("please add a name modifier for property enum '" + enumName.enumName() +
                        "' with properties " + propertiesA + " and values " + propertyValues.values +
                        " and/or properties" + propertiesB + " and values " + collision.values);
            }
        });

        // write enum properties and property enums
        propertyEnums.forEach((identifier, propertyEnum) ->
                writeFiles(JavaFile.builder(enumsPackageName, generateEnum(propertyEnum, identifier)).indent("    ").build()));
        final ClassName enumPropertyImpl = ClassName.get(packageName, "EnumProperty");
        propertyFields.forEach((identifier, namedProperty) -> {
            final ClassName currentEnum = ClassName.get(enumsPackageName,
                    namedProperty.enumName.enumName());
            builder.addField(FieldSpec
                .builder(ParameterizedTypeName.get(implCN, currentEnum), identifier.constantName())
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer(
                        "new $T<>($S, $T::typedValueOf)",
                        enumPropertyImpl, namedProperty.property.name, currentEnum)
                .build()).build();
        });
    }

    private record NamedProperty(Identifier enumName, Property property) {}

    private TypeSpec generateEnum(PropertyValues propertyValues, Identifier identifier) {
        final ClassName enumCN = ClassName.get(enumsPackageName, identifier.enumName());
        final TypeSpec.Builder enumBuilder = TypeSpec
                .enumBuilder(enumCN)
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(ClassName.get(packageName, "PropertyEnum"))
                .addJavadoc("AUTOGENERATED by " + getClass().getSimpleName());

        final CodeBlock.Builder fromPropStringSwitch = CodeBlock.builder()
                .beginControlFlow("return switch (value)");
        final CodeBlock.Builder toPropStringSwitch = CodeBlock.builder()
                .beginControlFlow("return switch (this)");

        for (final String propertyValue : propertyValues.values) {
            final String enumValue = propertyValue.toUpperCase(Locale.US);
            enumBuilder.addEnumConstant(enumValue);
            fromPropStringSwitch.add("case $S -> $L;\n", propertyValue, enumValue);
            toPropStringSwitch.add("case $L -> $S;\n", enumValue, propertyValue);
        }
        fromPropStringSwitch.add("default -> null;\n");

        final MethodSpec.Builder typedValueOf = MethodSpec.methodBuilder("typedValueOf")
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                .addAnnotation(Nullable.class)
                .addParameter(ParameterSpec.builder(String.class, "value").build())
                .returns(enumCN).addCode(fromPropStringSwitch.unindent().add("};").build());
        final MethodSpec.Builder untypedValue = MethodSpec.methodBuilder("untypedValue")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class).addAnnotation(NotNull.class)
                .returns(String.class).addCode(toPropStringSwitch.unindent().add("};").build());
        final MethodSpec.Builder property = MethodSpec.methodBuilder("property")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class);
        if (propertyValues.properties.size() == 1) {
            property.addCode("return $S;", propertyValues.properties.keySet().iterator().next())
                    .addAnnotation(NotNull.class);
        } else {
            property.addCode("return null;")
                    .addAnnotation(Nullable.class);
        }

        enumBuilder.addMethod(property.build()).addMethod(untypedValue.build())
                .addMethod(typedValueOf.build());

        return enumBuilder.build();
    }

    private record Identifier(String[] words) {
        Identifier(String blockIdentifier) {
            this(blockIdentifier.split("_"));
        }

        String constantName() {
            return Arrays.stream(words)
                    .map((word) -> word.toUpperCase(Locale.US))
                    .collect(Collectors.joining("_"));
        }

        String enumName() {
            return Arrays.stream(words).map((word) -> {
                if (word.length() <= 1) return word.toUpperCase(Locale.US);
                final char[] letters = word.toCharArray();
                letters[0] = Character.toUpperCase(letters[0]);
                return String.valueOf(letters);
            }).collect(Collectors.joining());
        }

        Identifier withPrefix(String[] words) {
            final String[] newWords = new String[this.words.length + words.length];
            System.arraycopy(words, 0, newWords, 0, words.length);
            System.arraycopy(this.words, 0, newWords, words.length, this.words.length);
            return new Identifier(newWords);
        }

        int indexOf(String word) {
            for (int i = 0; i < words.length; i++) {
                if (words[i].equals(word)) return i;
            }
            return -1;
        }

        @Override
        public boolean equals(Object o) {
            if (!(o instanceof Identifier(String[] otherWords))) return false;

            return Arrays.equals(words, otherWords);
        }

        @Override
        public int hashCode() {
            return Arrays.hashCode(words);
        }
    }

    private static final class Properties {
        final Map<List<String>, PropertyValues> properties = new LinkedHashMap<>();

        void registerProperties(Identifier block, JsonObject blockProperties) {
            blockProperties.entrySet().forEach(entry -> {
                final List<String> values = entry.getValue().getAsJsonArray().asList()
                        .stream().map(JsonElement::getAsString).toList();
                properties.computeIfAbsent(values, PropertyValues::new).registerBlock(entry.getKey(), block);
            });
        }

        void cleanEnums() {
            // Modifying while iterating a set is bad, use a list instead.
            final List<@Nullable List<String>> enums = new ArrayList<>(properties.keySet());
            for (int i = 0; i < enums.size(); i++) {
                final PropertyValues mergeSource = properties.get(enums.get(i));
                if (mergeSource == null) continue;
                for (int j = i + 1; j < enums.size(); j++) {
                    final PropertyValues mergeTarget = properties.get(enums.get(j));
                    if (mergeTarget == null) continue;
                    if (mergeTarget.tryMerge(mergeSource)) {
                        properties.remove(mergeSource.values);
                        break;
                    } else if (mergeSource.tryMerge(mergeTarget)) {
                        properties.remove(mergeTarget.values);
                    }
                }
            }
            properties.values().forEach(PropertyValues::trySplit);
        }
    }

    private static class PropertyValues {
        final List<String> values;
        final Map<String, Property> properties = new LinkedHashMap<>();
        final Map<List<String>, PropertyValues> subsets = new LinkedHashMap<>();
        @Nullable List<PropertyValues> split = null;

        // -1: unknown, 0: boolean, 1: integer, 2: enum
        private int type = -1;
        private @Nullable Identifier commonPart = null;

        private PropertyValues(List<String> values) {
            this.values = values;
        }

        private void registerBlock(String property, Identifier block) {
            properties.computeIfAbsent(property, _ -> new Property(property, values)).registerBlock(block);
        }

        int type() {
            if (type >= 0) return type;
            if (values.getFirst().equals("true")) {
                if (!values.get(1).equals("false")) {
                    throw new RuntimeException("Partial boolean found! properties: " +
                            properties.keySet().stream().toList());
                }
                type = 0; // boolean property
            } else if (values.stream().anyMatch(value -> value.charAt(0) >= '0' && value.charAt(0) <= '9')) {
                // java doesn't allow identifiers to start with numbers
                try {
                    int currentValue = Integer.parseInt(values.getFirst());
                    for (final Iterator<String> iterator = values.listIterator(1); iterator.hasNext(); ) {
                        final int nextValue = Integer.parseInt(iterator.next());
                        if (++currentValue != nextValue) {
                            throw new RuntimeException("non-continuous integer found! properties: " +
                                    properties.keySet().stream().toList());
                        }
                    }
                } catch (NumberFormatException _) {
                    throw new RuntimeException("Partial integer found! properties: " +
                            properties.keySet().stream().toList());
                }
                type = 1; // integer property
            } else {
                type = 2; // enum property
            }

            return type;
        }

        void trySplit() {
            if (commonPart().words.length != 0) return;
            final Map<String, Map<List<String>, PropertyValues>> suffixWordSorted = new LinkedHashMap<>();
            Stream.concat(Stream.of(this), subsets.values().stream()).forEach(propertyValues -> {
                for (final Property property : properties.values()) {
                    final Map<String, List<Identifier>> split = property.trySplit();
                    if (split == null) continue;
                    split.forEach((suffix, blocks) -> {
                        final Map<List<String>, PropertyValues> byValues = suffixWordSorted.computeIfAbsent(suffix,
                                _ -> new LinkedHashMap<>());
                        final PropertyValues splitValues = byValues.computeIfAbsent(propertyValues.values, PropertyValues::new);
                        blocks.forEach(block -> splitValues.registerBlock(property.name, block));
                    });
                }
            });
            if (suffixWordSorted.isEmpty()) return;


            // Don't make a bazillion enums/property constants.
            if (suffixWordSorted.size() > 2) {
                suffixWordSorted.values().stream()
                        .flatMap(byValues -> byValues.values().stream())
                        .forEach(propertyValues -> {
                            final PropertyValues target = propertyValues.values.equals(this.values) ?
                                    this : this.subsets.get(propertyValues.values);
                            propertyValues.properties.values().forEach(
                                    property -> property.blocks.forEach(
                                            block -> target.registerBlock(property.name, block)));
                });
                return;
            }

            // re-merge subsets
            split = suffixWordSorted.values().stream().map(byValues -> {
                final Iterator<PropertyValues> iterator = byValues.values().iterator();
                PropertyValues result = iterator.next();
                while (iterator.hasNext()) {
                    final PropertyValues current = iterator.next();
                    if (current.tryMerge(result)) {
                        result = current;
                    } else {
                        result.tryMerge(current);
                    }
                }
                return result;
            }).toList();
            commonPart = null;
        }

        boolean tryMerge(PropertyValues other) {
            if (other.values.size() >= this.values.size()) return false;
            if (other.properties.keySet().stream().noneMatch(properties::containsKey)) return false;
            // the lists are fairly small
            //noinspection SlowListContainsAll
            if (!this.values.containsAll(other.values)) return false;
            this.subsets.putAll(other.subsets);
            other.subsets.clear();
            this.subsets.put(other.values, other);
            return true;
        }

        Identifier getIdentifier() {
            final String enumPropertiesCombinedName;
            if (properties.size() == 1) {
                enumPropertiesCombinedName = properties.keySet().iterator().next();
            } else {
                enumPropertiesCombinedName = MULTI_PROPERTY_ENUM_NAMES.get(properties.keySet());
                if (enumPropertiesCombinedName == null) {
                    throw new RuntimeException("please add a combined name for the properties " + properties.keySet());
                }
            }
            return removeMatchingPart(commonPart(), enumPropertiesCombinedName);
        }

        Identifier commonPart() {
            if (commonPart != null) return commonPart;
            return commonPart = getCommonPart(
                    Stream.concat(
                            properties.values().stream(),
                            subsets.values().stream()
                                    .flatMap(subset -> subset.properties.values().stream())
                    ).map(Property::commonPart).toList()
            );
        }
    }

    private static class Property {
        final List<String> values;
        final String name;
        List<Identifier> blocks = new ArrayList<>();

        @Nullable
        private Identifier commonPart;
        private Map<String, List<Identifier>> suffixWordSorted = new LinkedHashMap<>(2);


        Property(String name, List<String> values) {
            this.name = name;
            this.values = values;
        }

        void registerBlock(Identifier block) {
            blocks.add(block);
            commonPart = null;
            suffixWordSorted.computeIfAbsent(block.words[block.words.length - 1],
                    (_) -> new ArrayList<>()).add(block);
        }

        void registerBlocks(Collection<Identifier> blocks) {
            for (final Identifier block : blocks) registerBlock(block);
        }

        @Nullable
        Map<String, List<Identifier>> trySplit() {
            if (commonPart().words.length > 0) return null;
            if (suffixWordSorted.size() <= 1 || suffixWordSorted.size() >= 4) return null;

            for (final var entry : suffixWordSorted.entrySet()) {
                final int groupSizeRatio = blocks.size() / (blocks.size() - entry.getValue().size());
                // split other blocks if this group is overwhelming for this property
                if (groupSizeRatio > 4) {
                    final Map<String, List<Identifier>> suffixWordSorted = this.suffixWordSorted;
                    suffixWordSorted.remove(entry.getKey());

                    // update caches
                    commonPart = null;
                    blocks = entry.getValue();
                    this.suffixWordSorted = new HashMap<>();
                    this.suffixWordSorted.put(entry.getKey(), entry.getValue());

                    return suffixWordSorted;
                }
            }
            return null;
        }

        Identifier getIdentifier() {
            return removeMatchingPart(commonPart(), name);
        }

        private Identifier commonPart() {
            if (commonPart != null) return commonPart;
            commonPart = getCommonPart(blocks);
            final Map<String, String> modifier = NAME_MODIFIERS.get(values);
            if (modifier == null) return commonPart;
            final String prefix = modifier.get(name);
            if (prefix == null) return commonPart;
            return commonPart = commonPart.withPrefix(prefix.split("_"));
        }
    }

    private static Identifier removeMatchingPart(Identifier commonPart, String property) {
        if (commonPart.words.length == 0) return new Identifier(property);

        final String[] propertyWords = property.split("_");
        for (final String commonWord : commonPart.words) {
            for (final String propertyWord : propertyWords) {
                if (commonWord.equals(propertyWord)) {
                    return new Identifier(propertyWords);
                }
            }
        }
        return new Identifier(propertyWords).withPrefix(commonPart.words);
    }

    private static Identifier getCommonPart(List<Identifier> blocks) {
        if (blocks.isEmpty()) return new Identifier(new String[0]);
        Identifier result = new Identifier(new String[0]);
        final Identifier first = blocks.getFirst();
        for (int i = 0; i < first.words.length; i++) {
            final String startWord = first.words[i];
            int maxLength = first.words.length - i;
            for (int j = 1; j < blocks.size(); j++) {
                final Identifier other = blocks.get(j);
                final int wordIdx = other.indexOf(startWord);
                if (wordIdx == -1) {
                    maxLength = 0;
                    break;
                }
                for (int k = 1; k < maxLength; k++) {
                    if (wordIdx + k >= other.words.length) {
                        maxLength = k;
                        break;
                    }
                    if (!other.words[wordIdx + k].equals(first.words[i + k])) {
                        maxLength = k;
                        break;
                    }
                }
            }
            if (result.words.length > maxLength || maxLength == 0) continue;
            result = new Identifier(Arrays.copyOfRange(first.words, i, i + maxLength));
        }
        return result;
    }
}
